// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFXQiMTqlaasHvogFBD7I0Fnxz_eWheg',
    appId: '1:853186466904:web:e2852b48bb266f2871a62d',
    messagingSenderId: '853186466904',
    projectId: 'mytodo-ba9f3',
    authDomain: 'mytodo-ba9f3.firebaseapp.com',
    storageBucket: 'mytodo-ba9f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFXQiMTqlaasHvogFBD7I0Fnxz_eWheg',
    appId: '1:853186466904:android:e2852b48bb266f2871a62d',
    messagingSenderId: '853186466904',
    projectId: 'mytodo-ba9f3',
    storageBucket: 'mytodo-ba9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFXQiMTqlaasHvogFBD7I0Fnxz_eWheg',
    appId: '1:853186466904:ios:e2852b48bb266f2871a62d',
    messagingSenderId: '853186466904',
    projectId: 'mytodo-ba9f3',
    storageBucket: 'mytodo-ba9f3.firebasestorage.app',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPFXQiMTqlaasHvogFBD7I0Fnxz_eWheg',
    appId: '1:853186466904:macos:e2852b48bb266f2871a62d',
    messagingSenderId: '853186466904',
    projectId: 'mytodo-ba9f3',
    storageBucket: 'mytodo-ba9f3.firebasestorage.app',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPFXQiMTqlaasHvogFBD7I0Fnxz_eWheg',
    appId: '1:853186466904:windows:e2852b48bb266f2871a62d',
    messagingSenderId: '853186466904',
    projectId: 'mytodo-ba9f3',
    storageBucket: 'mytodo-ba9f3.firebasestorage.app',
  );
} 